import Link from "next/link";
import { formatBps, formatCny } from "@/server/sample";
import { buildTrialRunCheckReportFromDb } from "@/server/trial-run-db-workflow";

export const dynamic = "force-dynamic";

export default async function TrialRunChecksPage() {
  const report = await buildTrialRunCheckReportFromDb();

  if (!report) {
    return (
      <>
        <header className="page-head">
          <div>
            <h1 className="page-title">Trial Run Checks</h1>
            <p className="page-subtitle">Import or enter a period before running checks.</p>
          </div>
          <span className="badge amber">no data</span>
        </header>
      </>
    );
  }

  return (
    <>
      <header className="page-head">
        <div>
          <h1 className="page-title">Trial Run Checks</h1>
          <p className="page-subtitle">
            HR and finance check whether orders, revenue, external profit, deposits, and pending reviews are clean before settlement.
          </p>
        </div>
        <span className={`badge ${report.canStartHrCalculation ? "green" : "amber"}`}>
          {report.canStartHrCalculation ? "Ready" : "Needs cleanup"}
        </span>
      </header>

      <section className="metric-grid">
        <div className="metric">
          <span>Current period</span>
          <strong>{report.periodCode}</strong>
        </div>
        <div className="metric">
          <span>Period status</span>
          <strong>{report.periodStatus}</strong>
        </div>
        <div className="metric">
          <span>Department target</span>
          <strong>{formatCny(report.departmentTargetCents)}</strong>
        </div>
        <div className="metric">
          <span>Commissionable revenue</span>
          <strong>{formatCny(report.commissionableRevenueCents)}</strong>
        </div>
        <div className="metric">
          <span>Achievement</span>
          <strong>{formatBps(report.achievementRateBps)}</strong>
        </div>
        <div className="metric">
          <span>Estimated pool</span>
          <strong>{formatCny(report.estimatedCommissionPoolCents)}</strong>
        </div>
      </section>

      <section className="panel">
        <div className="panel-head">
          <h2>Current Status / Next Step</h2>
          <span className={`badge ${report.canStartHrCalculation ? "green" : "amber"}`}>
            {report.canStartHrCalculation ? "HR can calculate" : "cleanup first"}
          </span>
        </div>
        <div className="panel-body">
          <table className="data-table">
            <tbody>
              <tr><th>Current period</th><td>{report.periodCode}</td></tr>
              <tr><th>Current Trial Run</th><td>Open / create from Trial Runs after data cleanup</td></tr>
              <tr><th>Current Settlement Run</th><td>Generated by HR after checks pass</td></tr>
              <tr><th>BLOCKER / MAJOR suggestions</th><td>{report.issueSuggestions.filter((issue) => ["BLOCKER", "MAJOR"].includes(issue.severity)).length}</td></tr>
              <tr><th>Can submit approval</th><td>{report.canStartHrCalculation ? "Yes, after HR calculates a run" : "No"}</td></tr>
              <tr><th>Can export</th><td>No. Export requires a boss-approved run.</td></tr>
              <tr>
                <th>Next action</th>
                <td>
                  {report.canStartHrCalculation
                    ? "HR creates Trial Run and calculates settlement."
                    : "Create issues for the listed blockers and finish cleanup before HR calculation."}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="panel">
        <div className="panel-head">
          <h2>Import and Ledger Counts</h2>
          <span className="badge blue">{report.periodCode}</span>
        </div>
        <div className="panel-body">
          <table className="data-table">
            <tbody>
              <tr><th>Department</th><td>{report.departmentName}</td></tr>
              <tr><th>Import batches</th><td>{report.importBatchCount} / {report.importBatchSources.join(", ")}</td></tr>
              <tr><th>Employees</th><td>{report.employeeCount}</td></tr>
              <tr><th>Vehicles</th><td>{report.vehicleCount}</td></tr>
              <tr><th>Orders</th><td>{report.orderCount}</td></tr>
              <tr><th>Rent receipts</th><td>{report.revenueReceiptCount}</td></tr>
              <tr><th>External profit receipts</th><td>{report.externalProfitReceiptCount}</td></tr>
              <tr><th>Deposits</th><td>{report.depositCount}</td></tr>
              <tr><th>Vehicle status events</th><td>{report.vehicleStatusEventCount}</td></tr>
              <tr><th>Target total</th><td>{formatCny(report.targetTotalCents)}</td></tr>
              <tr><th>Order receivable</th><td>{formatCny(report.orderReceivableCents)}</td></tr>
              <tr><th>Approved rent revenue</th><td>{formatCny(report.approvedRentRevenueCents)}</td></tr>
              <tr><th>Unapproved rent revenue</th><td>{formatCny(report.unapprovedRevenueCents)}</td></tr>
              <tr><th>Approved external profit</th><td>{formatCny(report.approvedExternalProfitCents)}</td></tr>
              <tr><th>External profit total</th><td>{formatCny(report.externalProfitTotalCents)}</td></tr>
              <tr><th>Historical recovered</th><td>{formatCny(report.historicalRecoveredCents)}</td></tr>
              <tr><th>Deposit total</th><td>{formatCny(report.depositTotalCents)}</td></tr>
              <tr><th>Abnormal deposits</th><td>{report.abnormalDepositCount}</td></tr>
              <tr><th>Unpaid orders</th><td>{report.unpaidOrderCount}</td></tr>
              <tr><th>Pending revenue</th><td>{report.pendingRevenueCount}</td></tr>
              <tr><th>Pending target adjustments</th><td>{report.pendingTargetAdjustmentCount}</td></tr>
              <tr><th>Approved target adjustments</th><td>{report.approvedTargetAdjustmentCount}</td></tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="panel">
        <div className="panel-head">
          <h2>Blocking Reasons</h2>
          <span className="badge amber">{report.blockingReasons.length}</span>
        </div>
        <div className="panel-body">
          {report.blockingReasons.length === 0 ? (
            <p className="empty-state">
              No blocker. Continue to <Link href="/commission/trial-runs">trial run workflow</Link>.
            </p>
          ) : (
            <ul className="workflow-list">
              {report.blockingReasons.map((reason) => (
                <li key={reason}>{reason}</li>
              ))}
            </ul>
          )}
        </div>
      </section>

      <section className="panel">
        <div className="panel-head">
          <h2>Issue Suggestions</h2>
          <span className="badge amber">{report.issueSuggestions.length}</span>
        </div>
        <div className="panel-body">
          {report.issueSuggestions.length === 0 ? (
            <p className="empty-state">No issue suggestion. Continue to trial run workflow.</p>
          ) : (
            <table className="data-table">
              <thead>
                <tr>
                  <th>Severity</th>
                  <th>Owner</th>
                  <th>Category</th>
                  <th>Title</th>
                  <th>Description</th>
                </tr>
              </thead>
              <tbody>
                {report.issueSuggestions.map((issue) => (
                  <tr key={`${issue.category}-${issue.title}`}>
                    <td>{issue.severity}</td>
                    <td>{issue.ownerRole}</td>
                    <td>{issue.category}</td>
                    <td>{issue.title}</td>
                    <td>{issue.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </section>
    </>
  );
}
